{
 "title": "Kuberntes Cluster Overview",
 "description": "This dashboard can help troubleshooting issue in k8s cluster at cluster, node and namespace level.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, clusterID)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kube_namespace_labels{cluster=\"$cluster\"})"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_created{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "kube_pod_container_info{namespace=\"$namespace\", cluster=\"$cluster\"}"
    }
   },
   {
    "name": "duration",
    "label": "Duration",
    "query": "10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overall cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster  node status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=~\"$cluster\", status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Namespaces ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(kube_namespace_created{cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=~\"$cluster\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "burstable  pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Besteffort  pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{cluster=~\"$cluster\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReadOnly PVC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly{cluster=~\"$cluster\"} != 0) "
    }
   ]
  },
  {
   "title": "Cluster age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_service_created{cluster=~\"$cluster\", namespace=\"default\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "cluster  node details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_info{cluster=~\"$cluster\"}"
    },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", pod!=\"\"}))"
    },
    {
     "expr": "((label_replace((node_memory_MemTotal_bytes{cluster=~\"$cluster\"}  + on(instance,cluster) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))  -  (label_replace((node_memory_MemAvailable_bytes{cluster=~\"$cluster\"}  + on(instance,cluster) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))) /  (label_replace((node_memory_MemTotal_bytes{cluster=~\"$cluster\"}  + on(instance,cluster) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\")) "
    },
    {
     "expr": "max\n  by(node) (max by(instance,clu) (kubelet_running_pod_count{ cluster=~\"$cluster\",job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance,cluster) group_left(node) kubelet_node_name{ cluster=~\"$cluster\",job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio{cluster=~\"$cluster\"} + on(instance,cluster) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    {
     "expr": "kube_node_role{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "cluster node readiness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=~\"$cluster\", status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Overall memory usage in cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\", pod!=\"POD\",namespace!=\"\"})",
     "legendFormat": "Total memory used"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\", resource=\"memory\"})",
     "legendFormat": "Total memory in cluster"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
    },
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason{cluster=~\"$cluster\"} !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "Node  wise load in cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{cluster=~\"$cluster\"} + on(instance, cluster) group_left(nodename) \nnode_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory usage in cluster by node",
   "type": "graph",
   "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{cluster=~\"$cluster\"}  + on(instance,cluster) group_left(nodename) \nnode_uname_info) - (node_memory_MemAvailable_bytes{cluster=~\"$cluster\"}  + on(instance,cluster) group_left(nodename) \nnode_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory usage by namespace in cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace)(container_memory_usage_bytes{cluster=~\"$cluster\", pod!=\"POD\",namespace!=\"\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall CPU usage in cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (instance) (irate(node_cpu_seconds_total{cluster=~\"$cluster\", mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance,cluster) group_left(nodename) \nnode_uname_info)",
     "legendFormat": "Total Used CPU in cluster"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\", resource=\"cpu\"})",
     "legendFormat": "Total CPU in cluster"
    }
   ]
  },
  {
   "title": "Node CPU usage[5m] in cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance,cluster,nodename) (irate(node_cpu_seconds_total{cluster=~\"$cluster\", mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance,cluster) group_left(nodename) \nnode_uname_info)",
     "legendFormat": "{{nodename}} "
    }
   ]
  },
  {
   "title": "Pod startup latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99,\n  sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{cluster=~\"$cluster\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{cluster=~\"$cluster\"}",
     "legendFormat": "{{node}} "
    }
   ]
  },
  { "title": "$node Node details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "$node uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " (\n (sum(time() - node_boot_time_seconds + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})) \nand \nON() kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"} == 1 \n)"
    }
   ]
  },
  {
   "title": "Node Type",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "(kube_node_role{node=\"$node\"})"
    },
    {
     "expr": "node_memory_Unevictable_bytes{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Node evictions",
   "type": "stat",
   "description": "Number of Node evictions that happened since current instance of NodeController started. Sampled every 60 seconds.\n",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_collector_evictions_number{pod=~\".*.$node.*\"})"
    },
    {
     "expr": "node_memory_Unevictable_bytes{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "pod count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{node=\"$node\",pod!=\"\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "besteffort pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",container=\"POD\",node=\"$node\"}))"
    }
   ]
  },
  {
   "title": "burstable pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id=~\".*.burstable.*\",node=\"$node\"}))"
    }
   ]
  },
  {
   "title": "guaranteed pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id!~\".*.burstable.*\",id!~\".*.besteffort.*\",node=\"$node\"}))"
    }
   ]
  },
  {
   "title": "Time synced",
   "type": "stat",
   "description": "Is clock synchronized to a reliable server (1 = yes, 0 = no). Sampled every 60 seconds.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_timex_sync_status) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"} ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node readiness for  $node ",
   "type": "graph",
   "description": "This panel shows the NotReady state of nodes. If any node goes in NotReady state, graph value will go from 1 to 0.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "node $node Memory/Disk/PID Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",node=\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Pod count by namespace on $node ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace)(container_memory_working_set_bytes{image!=\"\",node=\"$node\"})",
     "legendFormat": "{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "Pod startup latency ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99,\n  sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\",node=\"$node\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\",node=\"$node\"}",
     "legendFormat": "{{node}}"
    },
    {}
   ]
  },
  {
   "title": "Node $node load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{node=\"$node\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Node $node CPU usage",
   "type": "graph",
   "description": "record: instance:node_cpu_utilisation:rate1m\nexpr: 1\n  - avg without(cpu, mode) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m]))",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n((sum by (instance) (instance:node_cpu_utilisation:rate1m)) + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Total CPU requests on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores{node=\"$node\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Total CPU limits on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits_cpu_cores{node=\"$node\"})",
     "legendFormat": "total limits"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Node $node memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Total memory requests on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes{node=\"$node\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Total Memory limits on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits_memory_bytes{node=\"$node\"})",
     "legendFormat": "total liimits "
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "$node disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (nodename,device) (node_filesystem_avail_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"$node\"}))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Top 5  memory guzzling pods on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",node=\"$node\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5  memory guzzling pods on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",node=\"$node\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist_duration_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (node,le) (rate(kubelet_pleg_relist_duration_seconds_bucket{node=\"$node\"}[5m])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "node_timex_sync_status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_timex_sync_status) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"} ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "node_network_receive_errs_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_errs_total[5m]) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "node_network_transmit_errs_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_transmit_errs_total[5m]) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "NodeNumberConntrackEntriesUsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_nf_conntrack_entries * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})\n  / (node_nf_conntrack_entries_limit * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}) ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node network interface flaps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "changes(node_network_up{device!~\"veth.+\",job=\"node-exporter\"}[2m]) *  on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Namespace $namespace details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Namespace $namespace SLO over $duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\"}) \n/ \ncount without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "Error budget remaining for namespace: $namespace  over $duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\n\n(( avg(avg_over_time((sum without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\"}) \n/ \ncount without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\"}))[$duration:5m])\n)) - 0.98999999999999999 ) \n* \navg((time() - timestamp(up{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"} offset $duration)))\n\n"
    }
   ]
  },
  {
   "title": "total  pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", namespace=\"$namespace\",container=\"POD\"}))"
    }
   ]
  },
  {
   "title": "$namespace namespace creation time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_namespace_created{cluster=~\"$cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{cluster=~\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Ready pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{cluster=~\"$cluster\", namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=~\"$cluster\", namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{cluster=~\"$cluster\", namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "burstable  pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\", namespace=~\"$namespace\"}))\n"
    }
   ]
  },
  {
   "title": "Besteffort  pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Guaranteed  pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_spec_memory_reservation_limit_bytes{cluster=~\"$cluster\", namespace=\"$namespace\",container=\"POD\",id!~\".*.burstable.*|.*.besteffort.*\",id!~\".*.scope\",pod!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod readiness in $namespace namespace",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 77 },
   "format": "none",
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}::{{container}}"
    }
   ]
  },
  {
   "title": "Total CPU usage in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(namespace) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"POD\",image!=\"\",job=~\"kubelet|kubernetes-nodes-cadvisor\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": " CPU usage by pod in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"POD\",image!=\"\",job=~\"kubelet|kubernetes-nodes-cadvisor\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total CPU requests in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(namespace:kube_pod_container_resource_requests_cpu_cores:sum{cluster=~\"$cluster\", namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU throttling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum\n  by( namespace) (increase(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\", container!=\"\",namespace=~\"$namespace\"}[5m]))\n  / sum by( namespace) (increase(container_cpu_cfs_periods_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total memory requests in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 15, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum{namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total memory  usage by pods in $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(namespace) (container_memory_usage_bytes{cluster=~\"$cluster\", container!=\"POD\",image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "memory  usage by pods in $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 6, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(pod) (container_memory_usage_bytes{cluster=~\"$cluster\", container!=\"POD\",image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API server errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 86 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(reason) (aggregator_unavailable_apiservice_count{cluster=~\"$cluster\"})",
     "legendFormat": "{{name}}-{{reason}}"
    }
   ]
  },
  {
   "title": " $namespace pods on $node",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "count by (pod)(container_memory_usage_bytes{namespace=\"$namespace\",cluster=\"$cluster\", instance=~\"$node\" })",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "count by (pod)(container_memory_usage_bytes{namespace=\"$namespace\",cluster=\"$cluster\", node=~\"$node\" })",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod restarts in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=\"$namespace\"}[2m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod  $container node relation",
   "type": "graph",
   "description": "This panel shows pod node relation",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_info{cluster=~\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": " {{node}}::  {{pod}}"
    }
   ]
  },
  {
   "title": "pod $container state in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\",container=\"$container\"}) ",
     "legendFormat": "READY::{{pod}}::container $container"
    },
    {
     "expr": "(kube_pod_container_status_waiting{cluster=~\"$cluster\", namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "WAITING::{{pod}}::container $container "
    },
    {
     "expr": "(kube_pod_container_status_terminated{cluster=~\"$cluster\", namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "TERMINATED::{{pod}}::container $container"
    }
   ]
  },
  {
   "title": "PVCs available capacity in namespacee $namespace",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", namespace=\"$namespace\"}\n  / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=\"$namespace\"}\n ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "persistentvolumeclaim status in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_persistentvolumeclaim_access_mode{cluster=~\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{cluster=~\"$cluster\", namespace=\"$namespace\",phase=\"Bound\"}",
     "legendFormat": "Bound::{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVCs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{cluster=~\"$cluster\", phase=\"Failed\",namespace=\"$namespace\"} != 0) "
    }
   ]
  },
  {
   "title": "PVCs Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{cluster=~\"$cluster\", phase=\"Pending\",namespace=\"$namespace\"} != 0)"
    }
   ]
  },
  {
   "title": "Resource Quota in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$namespace\",resource=\"memory\"}/1024/1024/1024",
     "legendFormat": "{{resource}} GB"
    },
    {
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$namespace\",resource=\"storage\"}/1024/1024/1024",
     "legendFormat": "{{resource}} GB"
    }
   ]
  },
  {
   "title": "pods running in $namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"$namespace\"}"
    },
    {
     "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "kube_pod_info{namespace=\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Ingress in $namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_ingress_path{cluster=~\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "collapsed": true,
   "panels": [
    {
     "title": "API server status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{job=~\"apiserver|kubernetes-apiservers\", cluster=~\"$cluster\"} ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "API server availability over 30d",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 5, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1\n  - ((sum(increase(apiserver_request_duration_seconds_count{cluster=~\"$cluster\",verb=~\"POST|PUT|PATCH|DELETE\"}[30d]))\n  - sum(increase(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[30d])))\n  + (sum(increase(apiserver_request_duration_seconds_count{cluster=~\"$cluster\",verb=~\"LIST|GET\"}[30d]))\n  - (sum(increase(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\",le=\"0.1\",scope=\"resource\",verb=~\"LIST|GET\"}[30d]))\n  + sum(increase(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[30d]))\n  + sum(increase(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[30d]))))\n  + sum(increase(apiserver_request_total{cluster=~\"$cluster\",code=~\"5..\"}[30d]))) / sum(increase(apiserver_request_total{cluster=~\"$cluster\"}[30d]))"
      }
     ]
    },
    {
     "title": "API server certificate expiration time remaninig",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 11, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "apiserver_client_certificate_expiration_seconds_count{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"}\n  > 0 and on(job) histogram_quantile(0.01, sum by(job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"}[5m])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "apiserver_request:burnrate$duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 5, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "((sum(rate(apiserver_request_duration_seconds_count{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\",verb=~\"LIST|GET\"}[$duration]))\n  - (sum(rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\",le=\"0.1\",scope=\"resource\",verb=~\"LIST|GET\"}[$duration]))\n  + sum(rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[$duration]))\n  + sum(rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[$duration]))))\n  + sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"5..\",job=~\"apiserver|kubernetes-apiservers\",verb=~\"LIST|GET\"}[$duration])))\n  / sum(rate(apiserver_request_total{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\",verb=~\"LIST|GET\"}[$duration]))"
      }
     ]
    },
    {
     "title": "API server latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (verb)((cluster:apiserver_request_duration_seconds:mean5m{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"}\n  > on(verb) group_left() (avg by(verb) (cluster:apiserver_request_duration_seconds:mean5m{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"}\n  >= 0) + 2 * stddev by(verb) (cluster:apiserver_request_duration_seconds:mean5m{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"}\n  >= 0))) > on(verb) group_left() 1.2 * avg by(verb) (cluster:apiserver_request_duration_seconds:mean5m{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"}\n  >= 0) and on(verb, resource) cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\",quantile=\"0.99\"})",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "API server total requests by return code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(apiserver_request_total{cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "API server total requests by verb",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (verb) (rate(apiserver_request_total{cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "API server errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(verb) (rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"5..\",job=~\"apiserver|kubernetes-apiservers\"}[5m]))\n  / sum by(verb) (rate(apiserver_request_total{cluster=~\"$cluster\", job=~\"apiserver|kubernetes-apiservers\"}[5m]))",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "API aggregator_unavailable_apiservice_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(name, namespace) (increase(aggregator_unavailable_apiservice_count{cluster=~\"$cluster\"}[5m])) ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "API server total requests by resources",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (resource) (rate(apiserver_request_total{cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster SLO and Error budget",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster control plane SLO over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
      }
     ]
    },
    {
     "title": "Cluster control plane error budget remaining over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "\n\n(( avg(avg_over_time((sum without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)) - 0.98999999999999999 ) \n* \navg((time() - timestamp(up{job=~\"apiserver|kubernetes-apiservers\", cluster=~\"$cluster\"  } offset $duration)))\n\n"
      }
     ]
    },
    {
     "title": "Promtheus monitoring SLO over $duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(\navg_over_time((sum without ()(kube_pod_status_ready{cluster=~\"$cluster\", pod=~\"prometheus-operator-monitoring-operator.+|prometheus-rancher-monitoring-prometheus.+\",condition=\"true\"}) \n/ \ncount without ()(kube_pod_status_ready{cluster=~\"$cluster\", pod=~\"prometheus-operator-monitoring-operator.+|prometheus-rancher-monitoring-prometheus.+\"}))[$duration:5m])\n)"
      }
     ]
    }
   ]
  }
 ]
}