---
prometheus_version: latest
prometheus_targets: []

prometheus_scrape_configs:
- job_name: 'test-cluster'
  scrape_interval: 15s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{job="kubernetes-pods"}'
      - '{job="kubernetes-service-endpoints"}'
      - '{job="kubernetes-nodes"}'
      - '{job="kubernetes-apiservers"}'
      - '{job="kubernetes-service-endpoints"}'
  static_configs:
    - targets:
      - '192.168.101.201:80'
- job_name: 'test-mongodb'
  scrape_interval: 15s
  honor_labels: true
  metrics_path: '/metrics'
  # params: []
  static_configs:
    - targets:
      - 'mongodb:9100'
- job_name: 'test-rabbitmq'
  scrape_interval: 15s
  honor_labels: true
  metrics_path: '/metrics'
  # params: []
  static_configs:
    - targets:
      - 'rabbitmq:9100'